### PR TITLE
fix: correct prisma schema to work with suggested sqlite

### LINKED ISSUE #9: Database URL/Schema mismatch
It seems like there's a mismatch for the database URL in the prism schema:

`> npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:7
   | 
 6 |     provider = "postgresql"
 7 |     url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]`

### PR DESCRIPTION
**Pull request by barnjamin**
Never used prisma before but this allowed me to run `npx prisma db push` without errors

may close #9 and #8

### CODE REVIEW

**Comment by awtkns** [comment]
Hi all thanks for creating this! This was definitely an inconsistency on my part. I am looking at how we can better configure this as PostgresSQL is used in production. A couple options are to update to the documentation to:
- use postgres locally (not ideal as this makes it harder for others to start developing on) 
- provide a way of easily switching between sqllite and postgres depending on the environment. 

Atm this cant be merged as it would break prod. Thoughts? 🚀

**Comment by aljazceru** [comment]
> Hi all thanks for creating this! This was definitely an inconsistency on my part. I am looking at how we can better configure this as PostgresSQL is used in production. A couple options are to update to the documentation to:
> 
>     * use postgres locally (not ideal as this makes it harder for others to start developing on)
> 
>     * provide a way of easily switching between sqllite and postgres depending on the environment.
> 
> 
> Atm this cant be merged as it would break prod. Thoughts? rocket

make it configurable through .env

**Comment by barnjamin** [comment]
@tedspare that might be good enough to setup the right provider, but I also had to remove those `@db.Text` annotations which might be important to the postgres schema?

@awtkns if you can come up with something, feel free to submit a superseding pr, happy to close this one

**Comment by mrayonnaise** [comment]
I am guessing the annotations should be removed anyway if the goal is to make the system sort of DB-agnostic through configuration?

**Comment by Beats1393** [comment]
pretty cool

**Comment by awtkns** [comment]
Hey all this is now fixed main! (related #49). Thanks for the great feedback 🚀

**Comment by kevzy** [comment]
> Never used prisma before but this allowed me to run `npx prisma db push` without errors
> 
> may close #9 and #8

hey used this on mac but still got error.   npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:7
   |
 6 |     provider = "postgresql"
 7 |     url      = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

**Pull request closed without merging**
