### PR TITLE
Custom Sign in page added

### PR DESCRIPTION
**Pull request by abhithory**
Hello,

- In `next/src/server/auth/auth.ts` file =>  added custom page route for sign in page
- In `next/src/pages/signin.tsx` file => Developed entire Signin page

### CODE REVIEW

**Comment by asim-shrestha** [comment]
Thanks for doing this! Looks sweet. I updated the styling a bit

Can you please also enable this for local sign in? After that, it should be good to go :)

**Comment by abhithory** [comment]
@asim-shrestha , okay. i will do it

**Review by abhithory — COMMENTED** [review]
Hi @asim-shrestha ,

- I have added Sign in development. Please check it

**Comment by abhithory** [comment]
- i made some mistakes with git in local repo and that i pushed by mistake
- i will make new pull request with fresh code

**Pull request closed without merging**
