### PR TITLE
Fix typo vector_db_api_key

### PR DESCRIPTION
**Pull request by KennyDizi**
Fix typo vector_db_api_key

### CODE REVIEW

**Comment by asim-shrestha** [comment]
Thanks for catching this @KennyDizi 

Mind going over the prompt updates?

**Comment by KennyDizi** [comment]
you're welcome @asim-shrestha.
In my opinion this is a better one, and could we give it a try?

**Comment by asim-shrestha** [comment]
Can you talk about why you think its better? We just want to be really sure theres some data to back up changes like this

**Comment by KennyDizi** [comment]
@asim-shrestha Basically, it's a better paragraph, but I revert it, and this PR should contain only a fix for the typo.

**Comment by asim-shrestha** [comment]
Thanks @kenny-dinh-codeleap!

**Pull request merged**
