### PR TITLE
chore: show "Copied!" on copy click

### PR DESCRIPTION
**Pull request by hahayusuf**
Created a function that edits the text of the "copy" button to "copied!" when it is clicked.

### CODE REVIEW

**Comment by hahayusuf** [comment]
That's a good idea, thanks.

Will implement it.

**Comment by asim-shrestha** [comment]
Hey @hahayusuf great work! We should however avoid using document.getElementById when we can and use react standard ways to implement this. See the copy button used in message hover as an example

**Comment by hahayusuf** [comment]
I have updated it to add the timeout, and react referencing instead of elementId.

I appreciate your feedback. How is it after the last commit?

**Comment by hahayusuf** [comment]
Addressed by #84

**Pull request closed without merging**
