### PR TITLE
© copy button on top off header messages

### PR DESCRIPTION
**Pull request by jasangill1**
Start of PR

### CODE REVIEW

**Comment by asim-shrestha** [comment]
This is affecting the styling of the chat messages. Lets just only make this available if it is a task message

image

**Comment by asim-shrestha** [comment]
Lets use a ClipBoard icon instead of the copy icon. think chatgpt

image

**Comment by jasangill1** [comment]
do you want the thumbs up and down

**Comment by jasangill1** [comment]
Screen Shot 2023-06-28 at 6 23 52 PM


is that looking better?

**Comment by jasangill1** [comment]
Screen Shot 2023-06-28 at 7 47 30 PM

**Pull request merged**
