### PR TITLE
Fix flash of light mode on initial load

### PR DESCRIPTION
**Pull request by kevinlu1248**
Copied from https://github.com/kevinlu1248/AgentGPT/pull/13, by [Sweep](https://github.com/sweepai/sweep), an AI junior dev.

### Description
This PR addresses the issue of a brief flash of light mode during the initial load of the application, which is distracting for the user. The proposed solution is to create a JavaScript file that checks the user's preferred theme from local storage and applies it before the page loads. This file will be loaded using Next.js's Script component with a "beforeInteractive" strategy to ensure it runs before any other JavaScript. This approach should eliminate the flash by setting the correct theme before the page becomes interactive.

### Changes Made
- Created a new JavaScript file, `theme.js`, in the `public` directory to handle the theme setting before the page loads.
- Modified the `_app.tsx` file to include the `theme.js` file using the Next.js Script component with a "beforeInteractive" strategy.

Fixes https://github.com/reworkd/AgentGPT/issues/994

### CODE REVIEW

**Comment by kevinlu1248** [comment]
Based on the preview it seems mostly fixed and just the sides broken.

**Comment by asim-shrestha** [comment]
Hey @kevinlu1248 can you describe what this fixes? It appears the theme configuration is still not being correctly set (based on the sidebar light flash)

**Comment by kevinlu1248** [comment]
@asim-shrestha It bundles the script for automatically setting the correct theme colour to the top of the HTML ensuring it gets ran earlier before everything else is hydrated. I'll see if Sweep can do the sides as well.

**Comment by kevinlu1248** [comment]
Got Sweep to write a potential solution just now after looking through the dom tree for a bit

**Comment by jasangill1** [comment]
fixed

**Pull request closed without merging**
