### PR TITLE
feat: add combobox for model names

### PR DESCRIPTION
**Pull request by Jshen123**
**Description:**
Editable Combobox for model name
image

### CODE REVIEW

**Comment by Jshen123** [comment]
@awtkns , this PR will also resolve https://github.com/reworkd/AgentGPT/issues/98

**Comment by awtkns** [comment]
Ideally we want to use something [this](https://www.radix-ui.com/docs/primitives/components/select) for form elements like this. They are unstyled but implement things like keyboard nav etc..

**Comment by awtkns** [comment]
@Jshen123 It would also be good to give the option to input something that is not there :)

We can however merge this and improve after. up to you

**Review by awtkns — APPROVED** [review]
please see my comments :)

**Comment by Jshen123** [comment]
> @Jshen123 It would also be good to give the option to input something that is not there :)
> 
> We can however merge this and improve after. up to you

Hey @awtkns,  I like that flexibility. I have opened another PR that merges into this one with the editable option (https://github.com/reworkd/AgentGPT/pull/115)
image

**Comment by Jshen123** [comment]
> 



> Ideally we want to use something [this](https://www.radix-ui.com/docs/primitives/components/select) for form elements like this. They are unstyled but implement things like keyboard nav etc..

good call! we should definitely address accessibility in a later PR

**Comment by Jshen123** [comment]
Hi @awtkns  merged in editable combobox PR!  ready for PR to main ✅

**Comment by awtkns** [comment]
@Jshen123 seems there are some merge conflicts

**Comment by Jshen123** [comment]
> @Jshen123 seems there are some merge conflicts

Resolved!

**Pull request merged**
