### PR TITLE
fix : restyled layout Styling improvements #22

### PR DESCRIPTION
**Pull request by yuvrxj-afk**
-  Added overflow  property as hidden.

[Preview after Fix](https://drive.google.com/file/d/1rZ0NEhBzA3RMMv8tkKPlnlY72sY1z4RM/view?usp=share_link)

Resolves : #22

### CODE REVIEW

**Comment by yuvrxj-afk** [comment]
@awtkns

**Comment by ka-fuachie** [comment]
Setting the overflow property to hidden isn't the best. It removes the annoying content overflow but it's just cutting it off
Screenshot (153)

**Comment by yuvrxj-afk** [comment]
> Setting the overflow property to hidden isn't the best. It removes the annoying content overflow but it's just cutting it off
> 
> Screenshot (153)
> 
> 

It's happening with zoom right?

**Comment by ka-fuachie** [comment]
No, this is without zoom. I'm using my laptop with 1366 x 768 resolution. A little bit of scrolling has to be allowed for small screens

**Comment by ka-fuachie** [comment]
Checkout my pull request here #137

**Pull request closed without merging**
