### PR TITLE
Fix Dockerfile + missing env vars in example

### PR DESCRIPTION
**Pull request by tim-codes**
Just finished configuring the project locally and had to make a few corrections to get it working:
1. Platform Dockerfile was failing for missing pkg-config dependency
2. .env file required 2 more max-loops vars to startup properly

### CODE REVIEW

**Comment by asim-shrestha** [comment]
Thanks! Lets do the following instead

```
REWORKD_PLATFORM_MAX_LOOPS=${NEXT_PUBLIC_MAX_LOOPS}
```

Also note, if you run the setup commands (`./setup.sh` for mac) It should tell you when you have an out of date ENV value

**Comment by asim-shrestha** [comment]
Checking in @tim-codes :)

**Comment by tim-codes** [comment]
Hey @asim-shrestha thanks will update today :)

**Comment by tim-codes** [comment]
@asim-shrestha changes made. FYI I did do the setup.sh script originally, but still needed the env var amendments.

**Comment by asim-shrestha** [comment]
Thank you @tim-codes!

**Pull request merged**
