### PR TITLE
Fix for #65, default to .env API key if we are in development mode

### LINKED ISSUE #65: 🗯 Running locally, keeps asking for API key
Hello, I am running on localhost but it keeps asking for my API key. Is that expected behaviour?

### PR DESCRIPTION
**Pull request by astelmach01**
Fixed #65, needed to change NODE_ENV -> ENVIRONMENT since [this](https://nextjs.org/docs/messages/env-key-not-allowed)

### CODE REVIEW

**Comment by astelmach01** [comment]
API key is set in backend but not on frontend website

**Comment by astelmach01** [comment]
https://nextjs.org/docs/messages/env-key-not-allowed ^

**Review by awtkns — CHANGES_REQUESTED** [review]

**Comment by ruuderie** [comment]
Hey what do you guys need to get this PR merged?

**Comment by astelmach01** [comment]
Gonna fix rn

**Comment by awtkns** [comment]
This has been since fixed in the main branch, closing for now.

**Pull request closed without merging**
